- git: 
    repo: 'git@github.com:satiku/Docker-Compose.git'
    dest: /srv/docker-compose
    version: main

- name: start traefik docker-compose 
  docker_compose:
    project_src: /srv/docker-compose/traefik
    

- name: start readme docker-compose 
  docker_compose:
    project_src: /srv/docker-compose/readme
    

- name: start miniflux docker-compose 
  docker_compose:
    project_src: /srv/docker-compose/miniflux 

- name: start kanboard docker-compose 
  docker_compose:
    project_src: /srv/docker-compose/kanboard
    
- name: start node-red docker-compose 
  docker_compose:
    project_src: /srv/docker-compose/node-red
    
- name: start uptime-kuma docker-compose 
  docker_compose:
    project_src: /srv/docker-compose/uptime-kuma
    
- name: start jenkins docker-compose 
  docker_compose:
    project_src: /srv/docker-compose/jenkins
    
- name: start linkace docker-compose 
  docker_compose:
    project_src: /srv/docker-compose/linkace
    
- name: start audiobookshlef docker-compose 
  docker_compose:
    project_src: /srv/docker-compose/audio-bookshelf
    
- name: start quickshare docker-compose 
  docker_compose:
    project_src: /srv/docker-compose/quickshare
    
